config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'pets/new', to: "pets#new", as: :new_pet
  post 'pets', to: "pets#create"

  get 'pets/:id/edit', to: "pets#edit", as: :edit_pet
  patch 'pets/:id', to: "pets#update"

  delete 'pets/:id', to: "pets#destroy"

  get 'pets', to: 'pets#index'
  get 'pets/:id', to: 'pets#show', as: :pet
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  SPECIES = %w(dog cat capybara fish)
  validates :species, inclusion: { in: SPECIES }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save

    redirect_to pets_path
  end

  def edit
  end

  def update
    @pet.update(pet_params)

    redirect_to pets_path
  end

  def destroy
    @pet.destroy

    redirect_to pets_path
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :species, :address, :found_on)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <%= simple_form_for @pet do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :species, collection: %w(dog cat capybara fish) %>
        <%= f.input :found_on %>
      <%= f.button :submit, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/pets/edit.html.erb
<h1 class="text-center">Edit pet</h1>

<%= render 'form' %>

app/views/pets/index.html.erb
<div class="container">
  <h1>Lost pets</h1>
  <%= link_to "New Pet", new_pet_path, class: "btn btn-primary" %>
  <div class="row">
  <% @pets.each do |pet| %>
    <div class="col-sm-6">
        <p> <%= pet.name %></p>
        <p>Species: <%= pet.species %></p>
        <p>Address: <%= pet.address %></p>
        <p>Found_on: <%= pet.found_on %></p>

        <%= link_to "More info", pet_path(pet) %>
    </div>
  <% end %>
  </div>
</div>

app/views/pets/new.html.erb
<h1 class="text-center">Add pet</h1>

<%= render 'form' %>

app/views/pets/show.html.erb
<h1> <%= @pet.name %></h1>
<p>Species: <%= @pet.species %></p>
<p>Address: <%= @pet.address %></p>
<p>Found_on: <%= @pet.found_on %></p>

<%= link_to "Edit", edit_pet_path(@pet) %>
<%= link_to "Delete", pet_path(@pet), method: :delete %>

<%= link_to "Back", pets_path %>